package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.mycompany.myapp.Entities.CategorieMedicale;
import com.mycompany.myapp.Entities.Consultation;
import com.mycompany.myapp.Entities.Question;
import com.mycompany.myapp.Entities.User;
import com.mycompany.myapp.Gui.zohra.AfficherConsultationPatient;
import com.mycompany.myapp.Gui.zohra.AfficherToutesLesQuestions;
import com.mycompany.myapp.Gui.zohra.ListeCategorieMedicale;
import com.mycompany.myapp.Gui.zohra.ListeConsultation;
import com.mycompany.myapp.Gui.zohra.ModifierCategorieMedicale;
import com.mycompany.myapp.Gui.zohra.homeQuestion;
import com.mycompany.myapp.Services.ConsultationService;
import com.mycompany.myapp.Services.ReponseService;
import com.mycompany.myapp.Services.categorieMedicaleService;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        /*if(current != null){
            current.show();
            return;
        }
        Home h=new Home();
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        h.show();*/
        
        
        /*categorieMedicaleService c=new categorieMedicaleService();
        c.getAll();*/
       /* ReponseService r = new ReponseService();
        r.getAll();*/
     /* ConsultationService cons=new ConsultationService();
     cons.getAllPatient();*/
     
     User user=new User();
     user.setId(1);
     /*Question u= new Question(); 
        new AfficherToutesLesQuestions(u,user).show();*/
     CategorieMedicale c=new CategorieMedicale();
      //new ListeCategorieMedicale(c).show();
      new ModifierCategorieMedicale(c).show();
     
     
       //Consultation consultation=new Consultation();
       
       
      // new ListeConsultation(consultation,user).show();//medecin
      // new AfficherConsultationPatient(consultation,user).show(); //patient
        
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
